In [18]:
import linktransformer as lt
import pandas as pd
import numpy as np

In [3]:
file_path = '../data/restaurants.csv'
df = pd.read_csv(file_path)
df.head()

,name,address,city,phone,category,cluster
0,arnie morton's of chicago,435 s. la cienega blv.,los angeles,310/246-1501,american,0
1,arnie morton's of chicago,435 s. la cienega blvd.,los angeles,310-246-1501,steakhouses,0
2,art's delicatessen,12224 ventura blvd.,studio city,818/762-1221,american,1
3,art's deli,12224 ventura blvd.,studio city,818-762-1221,delis,1
4,hotel bel-air,701 stone canyon rd.,bel air,310/472-1211,californian,2

In [4]:
test_df = df.drop(columns='cluster')

test_df.head()

,name,address,city,phone,category
0,arnie morton's of chicago,435 s. la cienega blv.,los angeles,310/246-1501,american
1,arnie morton's of chicago,435 s. la cienega blvd.,los angeles,310-246-1501,steakhouses
2,art's delicatessen,12224 ventura blvd.,studio city,818/762-1221,american
3,art's deli,12224 ventura blvd.,studio city,818-762-1221,delis
4,hotel bel-air,701 stone canyon rd.,bel air,310/472-1211,californian

In [7]:
print([len(col) for col in df[['name', 'address', 'city', 'phone', 'category']].values.T])

[864, 864, 864, 864, 864]

In [33]:
# columns = ['name', 'phone']
# the function all_pair_combos_evaluate doesn't accept lists as input, only single strings
# to fix this we'll concatenate the columns into a single string

columns = ['name', 'phone']

df['name_phone'] = df[columns].apply(lambda x: ' '.join(x.dropna()), axis=1)

lt.infer.all_pair_combos_evaluate(
    df=df,
    model='sentence-transformers/multi-qa-mpnet-base-dot-v1',
    left_on='name_phone',
    right_on='name_phone',
)

2025-08-12 14:26:53 - Load pretrained SentenceTransformer: sentence-transformers/multi-qa-mpnet-base-dot-v1
2025-08-12 14:26:54 - You try to use a model that was created with version 3.0.0.dev0, however, your version is 2.3.1. This might cause unexpected behavior or errors. In that case, try to update to the latest version.



2025-08-12 14:26:55 - Use pytorch device_name: cpu

Batches: 100%|██████████| 7/7 [00:08<00:00,  1.16s/it]
Batches: 100%|██████████| 7/7 [00:08<00:00,  1.15s/it]

,left_on,right_on,score
0,arnie morton's of chicago 310/246-1501,arnie morton's of chicago 310/246-1501,1.000000
1,arnie morton's of chicago 310/246-1501,arnie morton's of chicago 310-246-1501,0.996978
2,arnie morton's of chicago 310/246-1501,art's delicatessen 818/762-1221,0.624263
3,arnie morton's of chicago 310/246-1501,art's deli 818-762-1221,0.673791
4,arnie morton's of chicago 310/246-1501,hotel bel-air 310/472-1211,0.475185
...,...,...,...
746491,wa-ha-ka oaxaca mexican grill 415-775-1055,ti couz 415-252-7373,0.593161
746492,wa-ha-ka oaxaca mexican grill 415-775-1055,trio cafe 415-563-2248,0.550466
746493,wa-ha-ka oaxaca mexican grill 415-775-1055,tu lan 415-626-0927,0.469878
746494,wa-ha-ka oaxaca mexican grill 415-775-1055,vicolo pizzeria 415-863-2382,0.527677
746495,wa-ha-ka oaxaca mexican grill 415-775-1055,wa-ha-ka oaxaca mexican grill 415-775-1055,1.000000